#!/usr/bin/env python

from __future__ import print_function
import sys, os, tty, termios

def getChar():
	def _ttyRead():
		fd = sys.stdin.fileno()
		oldSettings = termios.tcgetattr(fd)
		try:
			tty.setraw(fd)
			choice = sys.stdin.read(1)
		finally:
			termios.tcsetattr(fd, termios.TCSADRAIN, oldSettings)
		return choice
	return _ttyRead().lower()

edg = 'DarkBlueEdg/tools/edg'
os.system(edg)
sys.exit()
